[project]
name = "rag-pdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "altair==4",
    "faiss-cpu==1.7.4",
    "langchain==0.0.184",
    "langchain-community>=0.0.38",
    "langchain-google-genai>=1.0.4",
    "pypdf2==3.0.1",
    "python-dotenv==1.0.0",
    "streamlit==1.18.1",
]
